name: PR mode and quick fixes
on:
  workflow_dispatch:
  pull_request:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches
      - '*' # The all branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SPACE_REGISTRY }}
          username: ${{ secrets.SPACE_LOGIN }}
          password: ${{ secrets.SPACE_TOKEN }}
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QD_PRODUCT_INTERNAL_FEED: ${{ secrets.QD_PRODUCT_INTERNAL_FEED }}
          QD_PRODUCT_INTERNAL_AUTH: ${{ secrets.QD_PRODUCT_INTERNAL_AUTH }}
        with:
          pr-mode: true
          push-fixes: 'branch'
          commit-message: 'ðŸ¤– Apply quick-fixes by Funny Qodana to pull-request'
          use-nightly: true
          args: |
            --fail-threshold,0,
            --baseline,baseline_qodana.sarif.json,
            --baseline-include-absent,
            -l,qodana-jvm,--within-docker,false
